use crate::{
    LanePlan, Profile, ToolClass, ToolPolicy, ToolPolicyProvided, Trigger,
    runtime_profile_from_toml,
};

pub(crate) fn builtin_profiles() -> Vec<Profile> {
    [
        include_str!("../runtime/gh-runner.toml"),
        include_str!("../configs/runtime/gh-runner-standard.toml"),
        include_str!("../configs/runtime/gh-runner-full.toml"),
        include_str!("../runtime/cx23.toml"),
        include_str!("../runtime/cx33.toml"),
        include_str!("../runtime/cx43.toml"),
    ]
    .into_iter()
    .map(|profile| match runtime_profile_from_toml(profile) {
        Ok(profile) => profile,
        Err(err) => {
            eprintln!("fatal: parse builtin runtime profile: {err}");
            std::process::exit(2);
        }
    })
    .collect()
}

pub(crate) fn builtin_tools() -> Vec<ToolPolicy> {
    vec![
        tool(
            "tokmd",
            "tokmd",
            ToolClass::Packet,
            2,
            Trigger::Always,
            180,
            128,
            false,
            true,
        ),
        tool(
            "cargo-allow",
            "cargo-allow",
            ToolClass::Static,
            2,
            Trigger::SourceExceptionChanged,
            120,
            64,
            false,
            true,
        ),
        tool(
            "ast-grep",
            "ast-grep",
            ToolClass::Search,
            1,
            Trigger::SourceChanged,
            60,
            64,
            false,
            true,
        ),
        tool(
            "ripr",
            "ripr",
            ToolClass::Static,
            3,
            Trigger::RustBehaviorOrTestsChanged,
            240,
            128,
            false,
            true,
        ),
        tool(
            "unsafe-review",
            "unsafe-review",
            ToolClass::Static,
            3,
            Trigger::UnsafeOrNativeRiskChanged,
            240,
            128,
            false,
            true,
        ),
        tool(
            "semgrep",
            "semgrep",
            ToolClass::Security,
            3,
            Trigger::SourceChanged,
            180,
            128,
            false,
            false,
        ),
        tool(
            "actionlint",
            "actionlint",
            ToolClass::Workflow,
            1,
            Trigger::WorkflowChanged,
            60,
            32,
            false,
            true,
        ),
        tool(
            "zizmor",
            "zizmor",
            ToolClass::Workflow,
            2,
            Trigger::WorkflowChanged,
            120,
            64,
            false,
            true,
        ),
        tool(
            "gitleaks",
            "gitleaks",
            ToolClass::Security,
            2,
            Trigger::Diff,
            120,
            128,
            false,
            false,
        ),
        tool(
            "cargo-fmt",
            "cargo",
            ToolClass::Build,
            1,
            Trigger::Always,
            120,
            32,
            false,
            true,
        ),
        tool(
            "cargo-check",
            "cargo",
            ToolClass::Build,
            4,
            Trigger::Always,
            600,
            128,
            false,
            true,
        ),
        tool(
            "cargo-test",
            "cargo",
            ToolClass::Test,
            8,
            Trigger::Always,
            900,
            256,
            false,
            true,
        ),
        tool(
            "cargo-clippy",
            "cargo",
            ToolClass::Build,
            6,
            Trigger::Always,
            600,
            128,
            false,
            true,
        ),
        tool(
            "cargo-doc",
            "cargo",
            ToolClass::Build,
            4,
            Trigger::Always,
            600,
            128,
            false,
            true,
        ),
        tool(
            "artifact-verifier",
            "python",
            ToolClass::Static,
            2,
            Trigger::Always,
            120,
            32,
            false,
            true,
        ),
        tool(
            "coverage",
            "cargo",
            ToolClass::Coverage,
            6,
            Trigger::Manual,
            1_800,
            256,
            true,
            false,
        ),
        tool(
            "osv-scanner",
            "osv-scanner",
            ToolClass::Security,
            3,
            Trigger::DependencyChanged,
            180,
            128,
            false,
            false,
        ),
        tool(
            "cargo-audit",
            "cargo",
            ToolClass::Security,
            2,
            Trigger::DependencyChanged,
            120,
            64,
            false,
            false,
        ),
        tool(
            "cargo-deny",
            "cargo",
            ToolClass::Security,
            3,
            Trigger::DependencyChanged,
            180,
            128,
            false,
            false,
        ),
        tool(
            "shellcheck",
            "shellcheck",
            ToolClass::Static,
            1,
            Trigger::ShellChanged,
            60,
            32,
            false,
            true,
        ),
        tool(
            "cppcheck",
            "cppcheck",
            ToolClass::Static,
            3,
            Trigger::CppChanged,
            240,
            128,
            false,
            false,
        ),
        tool(
            "test",
            "cargo",
            ToolClass::Test,
            8,
            Trigger::Manual,
            900,
            256,
            true,
            true,
        ),
        tool(
            "build",
            "cargo",
            ToolClass::Build,
            12,
            Trigger::Manual,
            1_200,
            256,
            true,
            true,
        ),
        tool(
            "miri",
            "cargo",
            ToolClass::HeavyWitness,
            99,
            Trigger::Manual,
            1_800,
            256,
            true,
            true,
        ),
        tool(
            "cargo-mutants",
            "cargo",
            ToolClass::HeavyWitness,
            99,
            Trigger::Manual,
            1_800,
            256,
            true,
            true,
        ),
    ]
}

#[expect(
    clippy::too_many_arguments,
    reason = "tracked in policy/allow.toml#clippy-too-many-arguments-artifact-writers"
)]
pub(crate) fn tool(
    id: &str,
    command: &str,
    class: ToolClass,
    weight: u32,
    trigger: Trigger,
    timeout_sec: u64,
    artifact_budget_mb: u64,
    requires_lease: bool,
    enabled: bool,
) -> ToolPolicy {
    ToolPolicy {
        id: id.to_owned(),
        command: command.to_owned(),
        class,
        weight,
        default: trigger,
        required: false,
        timeout_sec,
        artifact_budget_mb,
        requires_lease,
        enabled,
        gate: None,
        // `provided` means "the repo config explicitly wrote this field".
        // Built-in tools were written by nobody's repo config, so every flag
        // is false: profile-level `[tool_timeouts]` overrides apply to them,
        // while a repo's explicit `[tools.<id>] timeout_sec` (provided =
        // true after the merge) stays the per-repo winner.
        provided: ToolPolicyProvided::default(),
    }
}

pub(crate) fn default_lanes() -> Vec<LanePlan> {
    vec![
        lane(
            "ub",
            "Native-boundary undefined-behavior review",
            "custom:MiniMax-M3-3",
            "MiniMax-M3",
            &["tokmd", "unsafe-review", "ast-grep", "ripr"],
            "Find stale pointer/length, RAB resize/detach/transfer/GC, worker handoff, active-view-region, JSC lifetime, FFI ownership, allocator, truncation, signedness, and overflow risks.",
        ),
        lane(
            "source-route",
            "Source route, sibling path, and claim verification",
            "custom:MiniMax-M3-3",
            "MiniMax-M3",
            &["tokmd", "ast-grep", "ripr"],
            "Trace public API to native path, sibling paths, helper callers, route variants, and PR claims. Call out overclaims and underclaims.",
        ),
        lane(
            "tests",
            "Red/green proof and oracle review",
            "custom:MiniMax-M3-3",
            "MiniMax-M3",
            &["tokmd", "ripr", "unsafe-review"],
            "Check whether tests fail on unpatched main, prove the changed behavior, observe post-capture mutations, and avoid smoke-only or tautological assertions.",
        ),
        lane(
            "arch",
            "Architecture, boundary, and smallest-complete-fix review",
            "custom:MiniMax-M3-3",
            "MiniMax-M3",
            &["tokmd", "unsafe-review", "ast-grep"],
            "Check boundary placement, helper shape, scope control, duplication risk, performance cost, and whether a smaller complete fix exists.",
        ),
        lane(
            "opposition",
            "Strongest substantiated objection review",
            "custom:MiniMax-M3-3",
            "MiniMax-M3",
            &["tokmd", "ripr", "unsafe-review", "ast-grep", "semgrep"],
            "Try to disprove the PR across correctness, test proof, performance, portability, source-route, and claim truth. Report serious issues outside focus too.",
        ),
        lane(
            "security",
            "Security and UB-as-exploit-primitive review",
            "custom:MiniMax-M3-3",
            "MiniMax-M3",
            &[
                "tokmd",
                "unsafe-review",
                "semgrep",
                "zizmor",
                "gitleaks",
                "osv-scanner",
                "cargo-audit",
                "cargo-deny",
            ],
            "Review STRIDE/OWASP and native-boundary exploitability: OOB, UAF, type confusion, size/offset overflow, information disclosure, DoS, secrets, crypto misuse, and workflow-token risk when present.",
        ),
    ]
}

pub(crate) fn lane(
    id: &str,
    role: &str,
    model: &str,
    model_display: &str,
    receives: &[&str],
    focus: &str,
) -> LanePlan {
    LanePlan {
        id: id.to_owned(),
        role: role.to_owned(),
        model: model.to_owned(),
        model_display: model_display.to_owned(),
        receives: receives.iter().map(|value| (*value).to_owned()).collect(),
        focus: focus.to_owned(),
    }
}
