//! One-command adoption: `ub-review enable` writes a safe GitHub Actions
//! workflow + minimal `.ub-review.toml` for the chosen review posture, then
//! prints the exact secret to add. This is the Droid/Factory-style first-run
//! path — the complexity stays inside the tool (#721).

use crate::*;
use std::fs;

const REQUIRED_CHECK: &str = "ub-review/gate";
const WORKFLOW_RELATIVE_PATH: &str = ".github/workflows/ub-review.yml";
const CONFIG_RELATIVE_PATH: &str = ".ub-review.toml";

/// Run `ub-review enable`. Validates the SHA pin, refuses to overwrite
/// existing files without `--force`, writes the workflow + minimal config,
/// and prints secret instructions.
pub(crate) fn cmd_enable(args: EnableArgs) -> Result<()> {
    validate_action_sha(&args.action_sha)?;
    if !matches!(args.model.as_str(), "minimax") {
        bail!(
            "--model {} is not supported in v0; only `minimax` is available",
            args.model
        );
    }
    let root = &args.root;
    let workflow_path = root.join(WORKFLOW_RELATIVE_PATH);
    let config_path = root.join(CONFIG_RELATIVE_PATH);

    // Refuse to clobber an existing ub-review setup unless the user opted in
    // with --force. Detecting existing ub-review workflows by name (not just
    // the exact path) avoids leaving two competing workflows behind.
    if !args.force {
        refuse_existing_config(&config_path)?;
        refuse_existing_workflow(root)?;
    }

    let workflow = render_enable_workflow(&args.action_sha, args.mode);
    let config = render_enable_config();

    let workflow_dir = workflow_path.parent().ok_or_else(|| {
        anyhow::anyhow!("workflow path {} has no parent", workflow_path.display())
    })?;
    fs::create_dir_all(workflow_dir)
        .with_context(|| format!("create {}", workflow_dir.display()))?;
    fs::write(&workflow_path, &workflow)
        .with_context(|| format!("write {}", workflow_path.display()))?;
    fs::write(&config_path, &config).with_context(|| format!("write {}", config_path.display()))?;

    print_enable_summary(&workflow_path, &config_path, args.mode, &args.action_sha);
    Ok(())
}

/// Reject anything that is not a full 40-character lowercase-or-uppercase hex
/// SHA. Mirrors `valid_setup_ci_action_sha` (`src/ci_audit.rs`): the generator
/// never invents a pin.
fn validate_action_sha(sha: &str) -> Result<()> {
    let trimmed = sha.trim();
    if trimmed.len() == 40 && trimmed.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Ok(());
    }
    bail!(
        "--action-sha must be the full 40-hex ub-review commit to pin in the generated workflow; got `{sha}`"
    );
}

fn refuse_existing_config(config_path: &Path) -> Result<()> {
    if config_path.exists() {
        bail!(
            "{} already exists; re-run with --force to overwrite",
            config_path.display()
        );
    }
    Ok(())
}

/// Scan `.github/workflows/` and refuse if any workflow references the
/// ub-review action. This catches a hand-written workflow under a different
/// filename, not just the default `ub-review.yml`.
fn refuse_existing_workflow(root: &Path) -> Result<()> {
    for scan in scan_local_workflows(root)? {
        if scan.path.contains("ub-review") {
            bail!(
                "existing ub-review workflow found at {}; re-run with --force to overwrite",
                scan.path
            );
        }
    }
    Ok(())
}

/// The MiniMax-on enable workflow. Distinct from `render_setup_ci_gate_workflow`
/// (which is deterministic-gate-only: `model-mode: off`, `posting:
/// artifact-only`). The enable template turns MiniMax review ON and uses the
/// `review-mode` preset (#720) so normal users never compose the internal
/// mode/fail-on-gate/review_forward knobs.
pub(crate) fn render_enable_workflow(action_sha: &str, mode: ReviewModePreset) -> String {
    let mode_key = mode.key();
    format!(
        r#"name: ub-review

# Generated by `ub-review enable`. MiniMax reviews each PR with specialist
# lanes, selects relevant PR-specific proof, runs it safely, and posts one
# review plus a CI gate result. See docs/QUICKSTART.md and docs/ADOPTION_MODES.md.
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ub-review-${{{{ github.event.pull_request.number || github.ref }}}}
  cancel-in-progress: true

jobs:
  ub-review:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      # Cache the ub-review source build so subsequent runs skip the ~12 min
      # cargo recompile. Keyed on the action SHA so a new pin invalidates.
      # This is critical for the source-build path (before a release artifact
      # exists): it cuts repeat runs from ~14 min to ~2-3 min, fast enough for
      # ub-review to post findings before human reviewers.
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target/ub-review-build"
          key: ub-review-{action_sha}

      - name: ub-review
        env:
          CARGO_TARGET_DIR: target/ub-review-build
        uses: EffortlessMetrics/ub-review@{action_sha}
        with:
          # review-mode hides the internal mode/fail-on-gate/review_forward
          # knobs. advisory = comment only; gate = recommended CI gate;
          # strict = + reporter verdict can block.
          review-mode: {mode_key}
          provider-policy: minimax-only
          minimax-api-key: ${{{{ secrets.MINIMAX_API_KEY }}}}
          github-token: ${{{{ github.token }}}}
          root: .
          base: origin/${{{{ github.base_ref }}}}
          head: HEAD
          out: target/ub-review
          posting: review

      - name: Upload ub-review artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ub-review-${{{{ github.event.pull_request.number || github.run_id }}}}
          path: target/ub-review
          if-no-files-found: warn
          retention-days: 7
"#
    )
}

/// The minimal `.ub-review.toml`. Deliberately NOT `Config::default()`, which
/// carries a hardcoded `repo.kind = "bun"` and a personal ledger path. The
/// enable config is generic; repos add proof/sensors/lanes later as the tool's
/// internal sophistication needs them.
pub(crate) fn render_enable_config() -> String {
    format!(
        r#"# ub-review config generated by `ub-review enable`.
# Repo-specific proof, sensors, and lanes can be added here later; this
# minimal config is enough for MiniMax review + the deterministic gate.

profile = "gh-runner"

[repo]
base = "origin/main"
head = "HEAD"

[gate]
required_check = "{REQUIRED_CHECK}"

# Post actionable findings (severity medium+ or confidence medium-high+) to
# the PR; suppress pure lane-status boilerplate. Without this, the default
# `suppress` policy posts nothing, so the acted-on-comment metric is
# structurally zero and a human can never cite a finding. See ub-review #717.
[review_body]
summary_only_body = "post_substantive"
"#
    )
}

fn print_enable_summary(
    workflow_path: &Path,
    config_path: &Path,
    mode: ReviewModePreset,
    sha: &str,
) {
    println!("ub-review enabled ({}, pinned to {sha}).", mode.key());
    println!();
    println!("  wrote {}", workflow_path.display());
    println!("  wrote {}", config_path.display());
    println!();
    println!("Next:");
    println!("  1. Add MINIMAX_API_KEY as a repository secret:");
    println!("       repo Settings → Secrets and variables → Actions → New repository secret");
    println!("  2. Commit the two files and open a pull request.");
    println!("  3. ub-review will post a MiniMax review and a CI gate result on the PR.");
    println!();
    println!("Mode `{}`:", mode.key());
    match mode {
        ReviewModePreset::Advisory => {
            println!("  MiniMax reviews and comments; the gate is non-required and never blocks.");
        }
        ReviewModePreset::Gate => {
            println!("  MiniMax reviews + the deterministic-floor gate is the required check.");
            println!("  Make `ub-review/gate` required in branch protection when ready.");
        }
        ReviewModePreset::Strict => {
            println!("  Gate + the reporter verdict (changes_requested/uncertain) can block.");
            println!("  Use only after calibration shows low false positives.");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enable_workflow_renders_review_mode_input() {
        for mode in [
            ReviewModePreset::Advisory,
            ReviewModePreset::Gate,
            ReviewModePreset::Strict,
        ] {
            let yaml = render_enable_workflow("aa".repeat(20).as_str(), mode);
            assert!(
                yaml.contains(&format!("review-mode: {}", mode.key())),
                "workflow for {mode:?} must set review-mode"
            );
            assert!(yaml.contains("@aa"), "workflow must pin the action SHA");
        }
    }

    #[test]
    fn enable_workflow_caches_source_build() {
        let sha = "c".repeat(40);
        let yaml = render_enable_workflow(&sha, ReviewModePreset::Gate);
        // The rust-cache step is critical for the source-build path: without it,
        // every run recompiles ~12 min of deps, making ub-review too slow to post
        // before human reviewers. The cache key must include the action SHA so a
        // new pin invalidates it.
        assert!(
            yaml.contains("Swatinem/rust-cache"),
            "workflow must cache the source build"
        );
        assert!(
            yaml.contains(&format!("key: ub-review-{sha}")),
            "cache key must be keyed on the action SHA"
        );
        assert!(
            yaml.contains("CARGO_TARGET_DIR"),
            "workflow must set CARGO_TARGET_DIR so the action reuses the cache"
        );
    }

    #[test]
    fn enable_workflow_uses_minimax_key_not_env() {
        let yaml = render_enable_workflow(&"b".repeat(40), ReviewModePreset::Gate);
        assert!(
            yaml.contains("${{ secrets.MINIMAX_API_KEY }}"),
            "workflow must reference the MINIMAX_API_KEY secret"
        );
        // Fork-safety guard: the secret reference must appear on the same line
        // as `minimax-api-key:` (inside the `with:` block), NOT in an `env:`
        // block. The CARGO_TARGET_DIR env var is fine (not a secret).
        for line in yaml.lines() {
            if line.contains("secrets.MINIMAX_API_KEY") {
                assert!(
                    line.contains("minimax-api-key:"),
                    "MINIMAX_API_KEY must only appear in the with: inputs, not env:; got: {line}"
                );
            }
        }
        // No pull_request_target trigger: that event runs on the base branch
        // and would expose secrets to fork-authored workflow runs.
        assert!(
            !yaml.contains("pull_request_target"),
            "workflow must not use pull_request_target (fork-safety)"
        );
        assert!(
            yaml.contains("persist-credentials: false"),
            "checkout must disable credential persistence (fork-safety)"
        );
    }

    #[test]
    fn enable_config_round_trips() -> Result<()> {
        let toml = render_enable_config();
        let config: Config = toml::from_str(&toml)?;
        assert_eq!(config.gate.required_check, REQUIRED_CHECK);
        assert_eq!(config.profile, "gh-runner");
        assert_eq!(config.repo.base, "origin/main");
        assert_eq!(config.repo.head, "HEAD");
        // post_substantive so actionable findings reach the PR (#717).
        assert_eq!(
            config.review_body.summary_only_body.key(),
            "post_substantive",
            "enable config must default to post_substantive so findings are actionable"
        );
        Ok(())
    }

    #[test]
    fn enable_config_is_not_the_bun_dogfood_default() {
        // The enable config must NOT carry the bun-dogfood defaults that
        // Config::default() ships (repo.kind="bun", personal ledger path).
        let toml = render_enable_config();
        assert!(
            !toml.contains("bun"),
            "enable config must not hardcode the bun repo kind"
        );
        assert!(
            !toml.contains("/home/steven"),
            "enable config must not carry the personal ledger path"
        );
    }

    #[test]
    fn enable_rejects_non_hex_action_sha() {
        // 39 hex chars (too short).
        assert!(validate_action_sha(&"a".repeat(39)).is_err());
        // 40 chars but non-hex.
        let mut non_hex = "z".repeat(40);
        non_hex = non_hex.replace('z', "g");
        let bad = format!("{non_hex}1"); // 41 chars, but test the 40-char non-hex path
        assert!(validate_action_sha(&bad[..40]).is_err());
        // 40 hex chars (valid).
        assert!(validate_action_sha(&"c".repeat(40)).is_ok());
        // Mixed case hex is accepted (GitHub SHAs are lowercase but tolerate both).
        assert!(validate_action_sha(&"D".repeat(40)).is_ok());
    }

    #[test]
    fn enable_refuses_overwrite_without_force() -> Result<()> {
        let temp = tempfile::tempdir()?;
        let root = temp.path();
        let config_path = root.join(CONFIG_RELATIVE_PATH);
        let workflow_path = root.join(WORKFLOW_RELATIVE_PATH);
        let workflow_dir = workflow_path
            .parent()
            .ok_or_else(|| anyhow::anyhow!("workflow path has no parent"))?;
        fs::create_dir_all(workflow_dir)?;

        // Pre-existing config without --force must refuse.
        fs::write(&config_path, "profile = \"gh-runner\"\n")?;
        let args = EnableArgs {
            mode: ReviewModePreset::Gate,
            model: "minimax".to_owned(),
            action_sha: "d".repeat(40),
            root: root.to_path_buf(),
            force: false,
        };
        assert!(cmd_enable(args).is_err());

        // With --force it proceeds even with the pre-existing config.
        fs::remove_file(&config_path)?; // reset
        fs::write(&config_path, "profile = \"gh-runner\"\n")?;
        let args = EnableArgs {
            mode: ReviewModePreset::Gate,
            model: "minimax".to_owned(),
            action_sha: "d".repeat(40),
            root: root.to_path_buf(),
            force: true,
        };
        cmd_enable(args)?;
        assert!(config_path.exists());
        assert!(workflow_path.exists());
        Ok(())
    }

    #[test]
    fn enable_refuses_existing_ub_review_workflow_by_name() -> Result<()> {
        let temp = tempfile::tempdir()?;
        let root = temp.path();
        let workflows = root.join(".github/workflows");
        fs::create_dir_all(&workflows)?;
        // A hand-written ub-review workflow under a non-default filename.
        fs::write(
            workflows.join("custom-ub-review.yml"),
            "name: ci\non:\n  pull_request:\njobs:\n  x:\n    runs-on: ubuntu-latest\n",
        )?;
        let args = EnableArgs {
            mode: ReviewModePreset::Gate,
            model: "minimax".to_owned(),
            action_sha: "e".repeat(40),
            root: root.to_path_buf(),
            force: false,
        };
        let err = match cmd_enable(args) {
            Ok(()) => anyhow::bail!("should have refused a competing ub-review workflow"),
            Err(err) => err.to_string(),
        };
        assert!(
            err.contains("existing ub-review workflow"),
            "should refuse a competing ub-review workflow: {err}"
        );
        Ok(())
    }

    #[test]
    fn enable_rejects_unsupported_model() -> Result<()> {
        let temp = tempfile::tempdir()?;
        let args = EnableArgs {
            mode: ReviewModePreset::Gate,
            model: "openai".to_owned(),
            action_sha: "f".repeat(40),
            root: temp.path().to_path_buf(),
            force: false,
        };
        let err = match cmd_enable(args) {
            Ok(()) => anyhow::bail!("should have rejected the unsupported openai model"),
            Err(err) => err.to_string(),
        };
        assert!(err.contains("not supported"), "should reject openai: {err}");
        Ok(())
    }
}
